### ISSUE TITLE
add `rust` `github`-integrated pipeline

### ISSUE THREAD

**Issue by Alexdelia** [justincapik/dslr#2]
need an automated `rust` pipeline with those jobs:

- [x] `cargo fmt`
- [x] `cargo check` (handled by `cargo clippy`)
- [x] `cargo doc` (handled by `cargo test`)
- [x] `cargo clippy`
- [x] `cargo test`

need comment (to discuss):

- [x] `typos` (using [typos](https://github.com/crate-ci/typos/tree/master))

[resource](https://github.com/Alexdelia/yahmrslib/blob/main/.github/workflows/rust.yml
)

might want to look into `git` `hooks` for the dev env

**Comment by Alexdelia** [comment]
@justincapik asking permission to `close` the `issue`

**Comment by justincapik** [comment]
sublime 🌠
