### ISSUE TITLE
`describe` `--full` option

### ISSUE THREAD

**Issue by Alexdelia** [justincapik/dslr#3]
`describe` must only print the interesting `csv` column by default

and will print the full summary if the `--full`/`-f` option is used

**Comment by Alexdelia** [comment]
finished on d6fd26e

**Comment by Alexdelia** [comment]
![image](https://github.com/justincapik/dslr/assets/60811847/fadf4691-31d3-4cdc-b1c2-239d409edc17)

**Comment by Alexdelia** [comment]
![image](https://github.com/justincapik/dslr/assets/60811847/484ab636-2f9a-4984-bba7-6313e8951fae)

**Comment by Alexdelia** [comment]
waiting for #1 to `merge` and close `issue`

**Comment by Alexdelia** [comment]
@justincapik, waiting for opinion

what do you prefer:
1. to **include**
2. to **skip**

`Index` column in `describe` without `--full`

**Comment by justincapik** [comment]
@Alexdelia it seems more intuitive to include any valid column of numbers, an that would mean discriminating only on the fact that a column is named `index` which I don't find makes sense

**Comment by Alexdelia** [comment]
@justincapik, done in d2d6d72
